<?php

declare(strict_types=1);

return [
    'default' => 'warm_editorial',

    'contrast_requirements' => [
        ['foreground' => 'text', 'background' => 'background', 'minimum' => 4.5],
        ['foreground' => 'muted', 'background' => 'background', 'minimum' => 4.5],
        ['foreground' => 'text', 'background' => 'surface', 'minimum' => 4.5],
        ['foreground' => 'muted', 'background' => 'surface', 'minimum' => 4.5],
        ['foreground' => 'accent', 'background' => 'background', 'minimum' => 4.5],
        ['foreground' => 'accent', 'background' => 'surface', 'minimum' => 4.5],
        ['foreground' => 'on_accent', 'background' => 'accent', 'minimum' => 4.5],
    ],

    'themes' => [
        'warm_editorial' => [
            'label' => 'Warm Editorial',
            'description' => 'A warm paper profile with PetSocial terracotta accents.',
            'background' => '#fbf6ee',
            'surface' => '#fffdf8',
            'text' => '#201914',
            'muted' => '#4c4037',
            'accent' => '#8f3f24',
            'accent_hover' => '#6f301b',
            'accent_soft' => '#f0d8ca',
            'on_accent' => '#fffdf8',
            'tab_underline' => '#8f3f24',
            'texture' => 'radial-gradient(circle at 12% 18%, rgba(143, 63, 36, 0.08), transparent 30%), radial-gradient(circle at 86% 12%, rgba(47, 91, 79, 0.07), transparent 28%)',
        ],
        'meadow' => [
            'label' => 'Meadow',
            'description' => 'A soft green profile with calm botanical accents.',
            'background' => '#f3f8ee',
            'surface' => '#fdfff9',
            'text' => '#172018',
            'muted' => '#3e4d3b',
            'accent' => '#2f6b45',
            'accent_hover' => '#245235',
            'accent_soft' => '#dcebdd',
            'on_accent' => '#ffffff',
            'tab_underline' => '#2f6b45',
            'texture' => 'radial-gradient(circle at 14% 14%, rgba(47, 107, 69, 0.09), transparent 28%), radial-gradient(circle at 92% 78%, rgba(194, 122, 48, 0.08), transparent 30%)',
        ],
        'lagoon' => [
            'label' => 'Lagoon',
            'description' => 'A bright blue-green profile with clean aquatic accents.',
            'background' => '#eef7f7',
            'surface' => '#fbfefe',
            'text' => '#152123',
            'muted' => '#384d51',
            'accent' => '#1f6670',
            'accent_hover' => '#194e56',
            'accent_soft' => '#d7eaec',
            'on_accent' => '#ffffff',
            'tab_underline' => '#1f6670',
            'texture' => 'radial-gradient(circle at 10% 20%, rgba(31, 102, 112, 0.09), transparent 32%), radial-gradient(circle at 90% 20%, rgba(76, 128, 93, 0.08), transparent 30%)',
        ],
        'marigold' => [
            'label' => 'Marigold',
            'description' => 'A sunlit cream profile with deep golden accents.',
            'background' => '#fff8e8',
            'surface' => '#fffef8',
            'text' => '#241c10',
            'muted' => '#56452a',
            'accent' => '#7a4b00',
            'accent_hover' => '#5e3900',
            'accent_soft' => '#f3dfb5',
            'on_accent' => '#ffffff',
            'tab_underline' => '#7a4b00',
            'texture' => 'radial-gradient(circle at 16% 18%, rgba(122, 75, 0, 0.09), transparent 30%), radial-gradient(circle at 84% 84%, rgba(143, 63, 36, 0.08), transparent 32%)',
        ],
        'berry' => [
            'label' => 'Berry',
            'description' => 'A gentle rose profile with rich berry accents.',
            'background' => '#fbf1f3',
            'surface' => '#fffafb',
            'text' => '#24171b',
            'muted' => '#533c43',
            'accent' => '#7b3144',
            'accent_hover' => '#612535',
            'accent_soft' => '#efd8de',
            'on_accent' => '#ffffff',
            'tab_underline' => '#7b3144',
            'texture' => 'radial-gradient(circle at 15% 18%, rgba(123, 49, 68, 0.09), transparent 30%), radial-gradient(circle at 88% 18%, rgba(47, 91, 79, 0.07), transparent 28%)',
        ],
    ],
];
